### ISSUE TITLE
how to run your code in jupyternotebook

### ISSUE THREAD

**Issue by zzzlxhhh** [RafayAK/NothingButNumPy#3]
Thx for your amazing work! I learnt a lot from your work.However, i dont know how to run the code in notebook. i dont know how to import util module. So what should i do to run this .ipynb.

**Comment by zzzlxhhh** [comment]
well i fix it by myself! sorry for interupt

**Comment by RafayAK** [comment]
@zzzlxhhh Thanks a lot for checking out this repo, I'm glad you are enjoying the content and have been able to run the notebooks 👍️. 
I'll add a "How to run?" guide in the readmes.
